config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#accueil'
  get '/new', to:'users#new', as: 'ajoutuser'
  post '/new', to:'users#create'
  get '/users/:id', to:'users#show', as:'pageprofil'
  get 'show/:id', to:'users#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def accueil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end

  def create
    @user = User.new
    @user.username = params[:username]
    @user.bio = params[:bio]
    @user.save
    redirect_to "/show/#{@user.id}"
  end

  def show
    @user=User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonPremierSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/accueil.html.erb
<h1>StaticPages#accueil</h1>
<p>Find me in app/views/static_pages/accueil.html.erb</p>

Bienvenue sur ma page d'accueil
Pour créer un utilisateur, c'est par ici <a href="<%=ajoutuser_path%>" > cliquez ici</a>

app/views/users/new.html.erb
<h1>Users#utilisateurs</h1>
<p>Find me in app/views/users/new.html.erb</p>
<h2>HTML Forms</h2>

<%= form_tag "/new", method: "post" do%>
  Comment vous appelez-vous ?<br>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="text" name="username" value="votre prénom">
  #username renvoie à la colonne du même nom dans la table user<br>
  Votre bio<br>
  <textarea type="text" name="bio" value="votre nom">
  </textarea><br><br>
  <input type="submit" value="Submit">
<%end%>

<p>Bienvenue dans la création d'utilisateurs !</p>

app/views/users/show.html.erb
<h1>Users#utilisateurs</h1>
<p>Find me in app/views/users/show.html.erb</p>
Bienvenue username <%=@user.username%>.<br>
Ton identifiant user est <%=@user%>.